/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Richiesta  di completamento operazione
 * @export
 * @interface AorStartTransactionRequest
 */
export interface AorStartTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'versionToken': string;
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'fileKey': string;
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'operationId': string;
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'recipientTaxId': string;
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'recipientType'?: AorStartTransactionRequestRecipientTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'delegateTaxId'?: string;
    /**
     * Data/ora di completamento della transazione,  espressa in formato RFC3339.
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'operationDate'?: string;
    /**
     * Checksum SHA256 del file caricato nella chiamata di documetUpload, esepresso in base64
     * @type {string}
     * @memberof AorStartTransactionRequest
     */
    'checksum': string;
}

export const AorStartTransactionRequestRecipientTypeEnum = {
    Pf: 'PF',
    Pg: 'PG'
} as const;

export type AorStartTransactionRequestRecipientTypeEnum = typeof AorStartTransactionRequestRecipientTypeEnum[keyof typeof AorStartTransactionRequestRecipientTypeEnum];


