/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Campi per poter applicare filtri sui dati a DB
 * @export
 * @interface FilterRequest
 */
export interface FilterRequest {
  /**
   * Data/ora in formato RFC3339.
   * @type {string}
   * @memberof FilterRequest
   */
  from?: string;
  /**
   * Data/ora in formato RFC3339.
   * @type {string}
   * @memberof FilterRequest
   */
  to?: string;
  /**
   * Tipologia Soggetto (PF/PG).
   * @type {string}
   * @memberof FilterRequest
   */
  recipientType?: string;
}
