/* tslint:disable */
/* eslint-disable */
/**
 * Piattaforma Notifiche: API del BFF dei servizi RADD
 * API utilizzate dal Backend for Frontend dei servizi RADD.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OperationResponseStatusAllOf } from './operation-response-status-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { ResponseStatus } from './response-status';

/**
 * @type OperationResponseStatus
 * Stato della response
 * @export
 */
export type OperationResponseStatus = OperationResponseStatusAllOf & ResponseStatus;
