/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OperationDetailResponse } from './operation-detail-response';
// May contain unused imports in some cases
// @ts-ignore
import { OperationResponseStatus } from './operation-response-status';

/**
 * Risposta della notifica
 * @export
 * @interface OperationResponse
 */
export interface OperationResponse {
    /**
     * 
     * @type {OperationDetailResponse}
     * @memberof OperationResponse
     */
    'element'?: OperationDetailResponse;
    /**
     * 
     * @type {boolean}
     * @memberof OperationResponse
     */
    'result'?: boolean;
    /**
     * 
     * @type {OperationResponseStatus}
     * @memberof OperationResponse
     */
    'status'?: OperationResponseStatus;
}

