/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Dettagli della response
 * @export
 * @interface OperationDetailResponse
 */
export interface OperationDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'operationStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'operationType'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OperationDetailResponse
     */
    'iuns'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'iun'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'operationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'fileKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'qrCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'recipientTaxId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'recipientType'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'delegateTaxId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'uid'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'operationStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'operationEndDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDetailResponse
     */
    'errorReason'?: string;
}

