/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dettagli della response Act
 * @export
 * @interface OperationActDetailResponse
 */
export interface OperationActDetailResponse {
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  operationStatus?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  operationType?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  iun?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  operationId?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  fileKey?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  qrCode?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  recipientTaxId?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  recipientType?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  delegateTaxId?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  uid?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  operationStartDate?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  operationEndDate?: string;
  /**
   *
   * @type {string}
   * @memberof OperationActDetailResponse
   */
  errorReason?: string;
}
