/* tslint:disable */
/* eslint-disable */
/**
 * Piattaforma Notifiche: API del BFF dei servizi RADD
 * API utilizzate dal Backend for Frontend dei servizi RADD.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OperationResponseStatusAllOf
 */
export interface OperationResponseStatusAllOf {
  /**
   * Return code. * 0 -> OK * 1 -> Nessun elemento associato * 99 -> KO
   * @type {number}
   * @memberof OperationResponseStatusAllOf
   */
  code?: OperationResponseStatusAllOfCodeEnum;
}

export const OperationResponseStatusAllOfCodeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_99: 99,
} as const;

export type OperationResponseStatusAllOfCodeEnum =
  (typeof OperationResponseStatusAllOfCodeEnum)[keyof typeof OperationResponseStatusAllOfCodeEnum];
