/* tslint:disable */
/* eslint-disable */
/**
 * Piattaforma Notifiche: API del BFF dei servizi RADD
 * API utilizzate dal Backend for Frontend dei servizi RADD. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Dettagli pratiche recuperate
 * @export
 * @interface OperationsDetailsResponse
 */
export interface OperationsDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'operationStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'operationType'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'iuns'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'operationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'fileKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'qrCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'recipientTaxId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'recipientType'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'delegateTaxId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'uid'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'operationStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'operationEndDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationsDetailsResponse
     */
    'errorReason'?: string;
}

