/* tslint:disable */
/* eslint-disable */
/**
 * API Piattaforma Notifiche
 * # Interface definition for Piattaforma Notifiche ## changelog   * ### 0.1     * First draft   * ### 0.2     * Second draft   * ### 1.0     * First version 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stato della response
 * @export
 * @interface StartTransactionResponseStatus
 */
export interface StartTransactionResponseStatus {
    /**
     * 
     * @type {string}
     * @memberof StartTransactionResponseStatus
     */
    'message'?: string;
    /**
     * Return code. * 0 -> OK * 99 -> KO * 2 -> NotReady 
     * @type {number}
     * @memberof StartTransactionResponseStatus
     */
    'code'?: StartTransactionResponseStatusCodeEnum;
    /**
     * Tempo, espresso in ms comunicato  al chiamante, trascorso il quale è possibile effettuare un nuovo tentativo di avvio della transazione.
     * @type {number}
     * @memberof StartTransactionResponseStatus
     */
    'retryAfter'?: number;
}

export const StartTransactionResponseStatusCodeEnum = {
    NUMBER_0: 0,
    NUMBER_99: 99,
    NUMBER_2: 2
} as const;

export type StartTransactionResponseStatusCodeEnum = typeof StartTransactionResponseStatusCodeEnum[keyof typeof StartTransactionResponseStatusCodeEnum];


